excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: false
    ignores_comments: true
    ignores_urls: true
function_body_length:
    error: 120
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    error: 600
    ignore_comment_only_lines: true
reporter: "xcode"

